// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMxp0AU9GjljRdgYYW-OQMcJyXGe047AA',
    appId: '1:1066138332696:web:e3888570f63f2a18971d6d',
    messagingSenderId: '1066138332696',
    projectId: 'music-2d406',
    authDomain: 'music-2d406.firebaseapp.com',
    storageBucket: 'music-2d406.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD8p6O0ATNY17nAnFfKkHxgLwX-BexEf0',
    appId: '1:1066138332696:android:017ecef447945f1a971d6d',
    messagingSenderId: '1066138332696',
    projectId: 'music-2d406',
    storageBucket: 'music-2d406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1kQnz8llRftl2FmPUQZKqlalBHa8E9o',
    appId: '1:1066138332696:ios:83c62d4d6a4324a7971d6d',
    messagingSenderId: '1066138332696',
    projectId: 'music-2d406',
    storageBucket: 'music-2d406.appspot.com',
    iosBundleId: 'com.example.musicsl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1kQnz8llRftl2FmPUQZKqlalBHa8E9o',
    appId: '1:1066138332696:ios:309e9abb580a7a11971d6d',
    messagingSenderId: '1066138332696',
    projectId: 'music-2d406',
    storageBucket: 'music-2d406.appspot.com',
    iosBundleId: 'com.example.musicsl.RunnerTests',
  );
}
